# Generated by Django 4.1.7 on 2023-02-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0004_alter_airport_name'),
        ('airlinex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='based_in',
            field=models.ForeignKey(default='DAVI', on_delete=django.db.models.deletion.CASCADE, related_name='based_in', to='airportx.airport'),
            preserve_default=False,
        ),
    ]
