# Generated by Django 4.1.6 on 2023-02-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0001_initial'),
        ('airlinex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='canceled',
            new_name='cancelled',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='canceled',
            new_name='cancelled',
        ),
        migrations.AlterField(
            model_name='employee',
            name='based_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_in', to='airportx.airport'),
        ),
    ]
