# Generated by Django 4.1.6 on 2023-03-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlinex', '0003_alter_employee_last_name_alter_passenger_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='married_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airlinex.employee'),
        ),
    ]
