# Generated by Django 4.1.6 on 2023-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlinex', '0003_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Extra notes'),
        ),
    ]
