# Generated by Django 4.1.6 on 2023-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Unique ICAO airport code')),
                ('name', models.CharField(max_length=100, verbose_name='Airport name')),
            ],
        ),
    ]
