# Generated by Django 4.1.7 on 2023-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportStats',
            fields=[
                ('icao_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Unique ICAO airport code')),
                ('average_delay', models.FloatField(verbose_name='Average Delay')),
                ('number_flights', models.IntegerField(verbose_name='Number of Flights')),
                ('number_bookings', models.IntegerField(verbose_name='Number of Passengers')),
            ],
            options={
                'db_table': 'airportx_airport',
                'managed': False,
            },
        ),
    ]
