# Generated by Django 4.1.6 on 2023-02-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0002_alter_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Airport name'),
        ),
    ]
