# Generated by Django 4.1.7 on 2023-02-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0002_airportstats'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airportstats',
            table='airport_stats',
        ),
    ]
