# Generated by Django 4.1 on 2023-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0003_alter_airportstats_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
