# Generated by Django 4.1.7 on 2023-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0004_alter_airport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportEmployees',
            fields=[
                ('icao_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Unique ICAO airport code')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Airport name')),
                ('num_employees', models.IntegerField(verbose_name='Number of Employees')),
            ],
            options={
                'db_table': 'airport_and_based_crew',
                'managed': False,
            },
        ),
    ]
