# Generated by Django 4.1 on 2023-03-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0004_airport_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='is_deleted',
        ),
    ]
