# Generated by Django 4.1.6 on 2023-03-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0005_remove_airport_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Runway length')),
                ('name', models.CharField(max_length=4, verbose_name='Runway name')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airportx.airport')),
            ],
        ),
    ]
